#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Stripe test-mode setup for issue #14.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# This repo keeps local config in .env.local, never .env (CLAUDE.md). Set here
# rather than editing the library above, which write_env reads at call time.
ENV_FILE=".env.local"

# ENV_FILE is relative, so refuse to write into whatever directory we happen to
# have been started from.
if [[ ! -f "package.json" ]] || ! grep -q '"name": *"ssuni-website"' package.json 2>/dev/null; then
  printf '\n  %s✗ Run this from the ssuni-website repo root.%s\n' "$YELLOW" "$RESET"
  printf '  %sIt writes .env.local relative to the current directory.%s\n\n' "$DIM" "$RESET"
  exit 1
fi

banner "Stripe test mode (issue #14)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Stripe account, in Test mode"
say "Test mode needs no business entity and no bank account, so this works"
say "while entity verification (#6) is still running in the background."
open_url "https://dashboard.stripe.com/test/apikeys"
step "Sign in, or create an account if you do not have one."
step "Check the dashboard header says 'Test mode'. Toggle it on if not."
warn "Every key below must start with pk_test_ or sk_test_."
warn "A live key here would take real money during development."
pause "Signed in and in Test mode?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "API keys"
say "From the API keys page that just opened:"
step "Copy the Publishable key (starts pk_test_)."
ask STRIPE_PUBLISHABLE_KEY "Paste the publishable key:"
step "On the Secret key row click 'Reveal test key', then copy it."
ask_secret STRIPE_SECRET_KEY "Paste the secret key (hidden):"
write_env STRIPE_PUBLISHABLE_KEY "$STRIPE_PUBLISHABLE_KEY"
write_env STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"
note "Neither takes a NEXT_PUBLIC_ prefix. That prefix is what ships a value to"
note "browsers: fatal for the secret key, and pointless for the publishable one"
note "because hosted Checkout (ADR 0008) runs entirely server-side."
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Stripe CLI -- needed for #18, NOT for #15"
say "The CLI supplies the local webhook signing secret and replays events at the"
say "webhook. The checkout route (#15) needs only the secret key already saved,"
say "so stages 3-5 can wait until #18 without blocking anything."
say ""
DO_CLI=0
if confirm "Set up the CLI now?"; then
  DO_CLI=1

  # The npm package @stripe/cli carries a platform allowlist with no
  # win32-arm64 entry, so it refuses before running anything. That is
  # gatekeeping, not a real incompatibility: the official release is x86_64 and
  # Windows on ARM runs it under emulation. Detect the broken shim, because it
  # sits on PATH and would otherwise look like a working install.
  if command -v stripe >/dev/null 2>&1 && ! stripe --version >/dev/null 2>&1; then
    warn "A non-working 'stripe' is on PATH:"
    note "  $(stripe --version 2>&1 | head -n1)"
    say "That is the npm wrapper refusing on arm64. Remove it first:"
    say ""
    say "    npm uninstall -g @stripe/cli"
    say ""
    pause "Removed it?"
  fi

  if command -v stripe >/dev/null 2>&1 && stripe --version >/dev/null 2>&1; then
    note "already working: $(stripe --version 2>&1 | head -n1)"
  elif command -v winget >/dev/null 2>&1; then
    say "Installing Stripe.StripeCli via winget (the official x86_64 zip)..."
    winget install --id Stripe.StripeCli -e \
      --accept-package-agreements --accept-source-agreements \
      || warn "winget install failed -- install by hand from the docs page."
    note "On arm64 this runs under Windows x64 emulation, which is fine for a CLI."
    warn "A fresh install is usually NOT on PATH in this shell. If the next stage"
    warn "cannot find 'stripe', close this terminal, open a new one, and re-run."
  else
    warn "winget not found. Install the CLI by hand:"
    open_url "https://docs.stripe.com/stripe-cli#install"
  fi
else
  SKIPPED+=("Stripe CLI, stripe login, and the local webhook signing secret (all #18)")
  note "Skipped. Re-run this wizard when #18 starts -- saved values are kept."
fi
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Pair the CLI with your account"
if (( DO_CLI )); then
  say "This opens a browser once to link the CLI to your Stripe account."
  if command -v stripe >/dev/null 2>&1 && stripe --version >/dev/null 2>&1; then
    say "Running: stripe login"
    stripe login || warn "stripe login did not complete -- run it by hand."
  else
    warn "'stripe' is not usable in this shell."
    say "Open a new terminal and run:"
    say ""
    say "    stripe login"
    say ""
    pause "Done that?"
  fi
else
  note "Skipped with stage 3 -- this is #18 work."
fi
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Webhook signing secret"
if (( DO_CLI )); then
  say "'stripe listen' runs in the foreground, so it needs its own terminal."
  say ""
  step "Open a SECOND terminal, cd to this repo, and run:"
  say ""
  say "    stripe listen --forward-to localhost:3000/api/stripe/webhook"
  say ""
  step "On startup it prints: 'Your webhook signing secret is whsec_...'"
  step "Copy that value, then come back here."
  ask_secret STRIPE_WEBHOOK_SECRET "Paste the signing secret (hidden):"
  write_env STRIPE_WEBHOOK_SECRET "$STRIPE_WEBHOOK_SECRET"
  note "Leave that terminal running whenever you test checkout locally."
  warn "This secret is for LOCAL forwarding only. The deployed worker needs its"
  warn "own secret from a real dashboard endpoint, which needs a public URL."
  note "The route /api/stripe/webhook does not exist yet -- #18 builds it and must"
  note "match this path. If it lands elsewhere, re-run stripe listen against that."
else
  note "Skipped with stage 3 -- this is #18 work."
  say "Without the CLI there is a second route to a signing secret, and it may"
  say "be the better one: deploy a preview to Cloudflare, register that public"
  say "URL as a webhook endpoint in the Stripe dashboard, and read its secret"
  say "there. That tests the real worker runtime rather than a local forward."
fi
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Written down for later, nothing to do now"
step "Production keys go in Cloudflare WORKER SECRETS"
say "  (Settings -> Variables and Secrets), never in Build variables."
say "  Build variables are not readable at request time, so the payment code"
say "  would simply find them absent -- with a green build and no error."
step "Switching to live keys and setting them there is issue #26."
step "The production webhook endpoint and its own signing secret is #26/#27,"
say "  once there is a real domain."
warn "Never give a Stripe key a NEXT_PUBLIC_ prefix."
pause

finish
